version: '3'
services:
  nginx:
    container_name: "nginx"
    build:
      context: ./docker/nginx
    depends_on:
      - php
    ports:
      - 8082:80
    volumes:
      - ./docker/nginx/logs:/etc/nginx/logs

  php:
    container_name: "php"
    build:
      context: ./docker/php
    depends_on:
      - mysql
    volumes:
      - ./src:/var/www/html/src
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini

  mysql:
    image: mysql:8.0.30
    container_name: "mysql"
    volumes:
      - db-store:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
    ports:
      - 13308:3306

volumes:
  db-store:
